server:
  port: 9000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # only dev, production can use validate
  datasource:
    username: material
    password: material
    url: jdbc:postgresql://localhost:5432/material_management
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8082/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://localhost:8082/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

logging:
  level:
    org.springframework.security: trace